### ISSUE TITLE
On Android cannot find the correct TESSDATA_PREFIX

### ISSUE THREAD

**Issue by cloudxxxx** [CTBConsulting/Card.io-for-Capital-One-vertical-Cards#13]
Using Android Studio the initialization of tesseract fails because the env variable TESSDATA_PREFIX is wrong.
In nativeRecognizer.cpp what is the correct path i should configure?
the actual one is obviously wrong but can't guess the correct one:

setenv("TESSDATA_PREFIX","/storage/emulated/0/Android/data/org.my.scanExample.debug/files/Tesseract/",1);

Shouldn't it be the one copied in "<...>env\card.io-Android-source\card.io\src\main\assets\" ?

**Comment by cloudxxxx** [comment]
My bad.
SimpleApp in the project copy the tessdata file  and prints the path in the console:
Accessing: /storage/emulated/0/Android/data/io.card.development/files/Tesseract/
Created directory /storage/emulated/0/Android/data/io.card.development/files/Tesseract/tessdata
Created directory /storage/emulated/0/Android/data/io.card.development/files/Tesseract/tessdata/tessconfigs

**Comment by CTBConsulting** [comment]
OK

Coley
