### ISSUE TITLE
[Q] How to use your enhanced library for Android?

### ISSUE THREAD

**Issue by hnvn** [CTBConsulting/Card.io-for-Capital-One-vertical-Cards#14]
I try to use your library in my Android project. But I have some problems. I already took a look at your document "Environment _Configuration_Android.pd", but I'm quite confused:
- To compile open “prebuilt/android/card.io-Android-source/” with Android Studio -> but this folder is empty
- I try to setup manually, but I don't know where to download OCRE source.
Please, give me some small advices. Thanks

**Comment by agustinsivoplas** [comment]
How to resolve this? I am stucked at same point. Thanks

**Comment by Chandrakala14** [comment]
I am also facing same issue, any suggestions .

**Comment by Mr-Torman** [comment]
also i'm stuck at the same problem any update
