### ISSUE TITLE
Testing the iOS version

### ISSUE THREAD

**Issue by IHEARTCOOKIES** [CTBConsulting/Card.io-for-Capital-One-vertical-Cards#21]
Hi there,

I took the liberty to print out the [Supported COF Cards.jpg](https://github.com/CTBConsulting/Card.io-for-Capital-One-vertical-Cards/blob/master/Supported%20COF%20Cards.jpg) to test out with both the master and dev branch. What I found was that no cards actually scanned. All of them passed the VSegScore's, however, none of them actually extracted any information from either of the cards. Instead, the phone buzzes for a split second then returns to the scanning page - without ever presenting the card number screen.

What can the problem be? Has anyone gotten this repo to work?

**Comment by CTBConsulting** [comment]
Yes the code does work
I’m assuming you were scanning actual cards not printed images. If so:
What type of credit cards were you testing?
Did classic embossed cards report correctly?
What smart phone and OS were you using?

CTB Consulting

**Comment by IHEARTCOOKIES** [comment]
My bad. The CC I tested with had a slightly different font. Didn't notice it at first. Thanks @CTBConsulting
